"""Configuration that fails closed (the fail-closed-config pattern, with this service's fields and rules).

Everything comes from the environment under the HUB_ prefix. Secrets are names in the secrets provider, never
values. `validate()` names every problem at once; the entrypoint's `check-config` refuses to serve a live process
with a missing gate. Fake identity is refused in production.
"""
from __future__ import annotations
import json, os, sys
from dataclasses import dataclass, field, fields

HERE = os.path.dirname(os.path.abspath(__file__))
SERVICE = os.path.dirname(HERE)


class ConfigError(Exception):
    pass


def _env(name: str, default: str | None = None) -> str | None:
    v = os.environ.get(name)
    return v if v not in (None, "") else default


@dataclass
class Settings:
    env: str = "sandbox"                                   # sandbox | staging | production
    auth: str = "mock"                                     # mock (dev personas; refused in production) | oidc
    listen_host: str = "127.0.0.1"
    listen_port: int = 8080
    public_url: str = "http://localhost:8080"
    db_path: str = ":memory:"                              # the record: briefs, requests, sign-offs; a file in staging and production
    idp_issuer: str = ""                                   # the bank's identity provider (OIDC issuer URL)
    idp_audience: str = ""                                 # the client id the hub's tokens are issued for
    idp_jwks_url: str = ""                                 # optional; derived from the issuer's discovery document when empty
    identity_map: str = os.path.join(SERVICE, "data", "identity-map.example.json")   # group ids -> roles, entitlements, teams, ladder
    consumers_file: str = os.path.join(SERVICE, "data", "consumers.example.json")    # the bank's own listings and registry
    collection_file: str = os.path.join(SERVICE, "data", "collection.json")          # generated by tools/shelf.py --write
    guide_file: str = os.path.join(SERVICE, "data", "guide-corpus.json")             # the guide's passages, generated by tools/shelf.py --write
    static_dir: str = ""                                   # the hub's built dist/, served with an SPA fallback; empty serves the API only
    kb_url: str = "/kb"
    assistant: str = "fake"                                # fake | http | bedrock
    assistant_url: str = ""                                # http: the platform runtime that streams turns
    assistant_token_name: str = "hub/assistant-token"      # http: the secret's name
    kb_search_url: str = ""                                # bedrock: the knowledge base's search endpoint for citations (optional)
    bedrock_region: str = ""
    bedrock_endpoint: str = ""                             # the bank's VPC endpoint in production
    bedrock_model_id: str = ""
    bedrock_inference_profile_arn: str = ""
    bedrock_max_output_tokens: int = 1500
    secrets: str = "env"                                   # env | file:<path> | aws
    ai_security_group: str = ""                            # the directory group whose members sign for AI security (oidc)
    owner_domain: str = ""                                 # the email domain an owner signs from (required with oidc; empty in the sandbox)
    # the hub's own runtime configuration, served as /config.js so one built dist runs everywhere
    web_oidc_authority: str = ""                           # the identity provider's OIDC authority for the browser (Authorization Code + PKCE)
    web_oidc_client_id: str = ""
    web_oidc_redirect_uri: str = ""                        # <HUB_PUBLIC_URL>/auth/callback when empty
    web_oidc_post_logout_uri: str = ""                     # <HUB_PUBLIC_URL>/ when empty
    web_oidc_scope: str = "openid profile email"
    max_body_bytes: int = 1_000_000
    rate_per_minute: int = 300                             # requests per person per minute (a token bucket); 0 disables
    idempotency_ttl_s: int = 86_400                        # how long a replayed answer is kept
    conversation_retention_days: int = 90                  # conversations older than this are deleted daily; 0 keeps them
    log_level: str = "INFO"
    build_sha: str = "dev"
    prefix: str = field(default="HUB_", repr=False)
    parse_errors: list = field(default_factory=list, repr=False)  # numbers that were not numbers; reported by validate()

    @classmethod
    def from_env(cls, prefix: str = "HUB_") -> "Settings":
        e = lambda k, d=None: _env(prefix + k, d)
        d = cls()
        errors: list[str] = []
        def num(k: str, default: int) -> int:
            raw = e(k, str(default))
            try:
                return int(raw)
            except (TypeError, ValueError):
                errors.append(f"{prefix}{k} must be an integer"); return default
        return cls(env=e("ENV", d.env), auth=e("AUTH", d.auth), listen_host=e("LISTEN_HOST", d.listen_host), listen_port=num("LISTEN_PORT", d.listen_port),
                   public_url=e("PUBLIC_URL", d.public_url), db_path=e("DB", d.db_path), idp_issuer=e("IDP_ISSUER", ""), idp_audience=e("IDP_AUDIENCE", ""),
                   idp_jwks_url=e("IDP_JWKS_URL", ""), identity_map=e("IDENTITY_MAP", d.identity_map), consumers_file=e("CONSUMERS_FILE", d.consumers_file),
                   collection_file=e("COLLECTION_FILE", d.collection_file), guide_file=e("GUIDE_FILE", d.guide_file), static_dir=e("STATIC_DIR", ""), kb_url=e("KB_URL", d.kb_url),
                   assistant=e("ASSISTANT", d.assistant), assistant_url=e("ASSISTANT_URL", ""), assistant_token_name=e("ASSISTANT_TOKEN_NAME", d.assistant_token_name),
                   kb_search_url=e("KB_SEARCH_URL", ""), bedrock_region=e("BEDROCK_REGION", os.environ.get("AWS_REGION", "") or ""), bedrock_endpoint=e("BEDROCK_ENDPOINT", ""),
                   bedrock_model_id=e("BEDROCK_MODEL_ID", ""), bedrock_inference_profile_arn=e("BEDROCK_INFERENCE_PROFILE_ARN", ""),
                   bedrock_max_output_tokens=num("BEDROCK_MAX_OUTPUT_TOKENS", d.bedrock_max_output_tokens), secrets=e("SECRETS", d.secrets),
                   ai_security_group=e("AI_SECURITY_GROUP", ""), owner_domain=e("OWNER_DOMAIN", ""), web_oidc_authority=e("WEB_OIDC_AUTHORITY", ""), web_oidc_client_id=e("WEB_OIDC_CLIENT_ID", ""),
                   web_oidc_redirect_uri=e("WEB_OIDC_REDIRECT_URI", ""), web_oidc_post_logout_uri=e("WEB_OIDC_POST_LOGOUT_URI", ""), web_oidc_scope=e("WEB_OIDC_SCOPE", d.web_oidc_scope),
                   max_body_bytes=num("MAX_BODY_BYTES", d.max_body_bytes), rate_per_minute=num("RATE_PER_MINUTE", d.rate_per_minute),
                   idempotency_ttl_s=num("IDEMPOTENCY_TTL_S", d.idempotency_ttl_s), conversation_retention_days=num("CONVERSATION_RETENTION_DAYS", d.conversation_retention_days),
                   log_level=e("LOG_LEVEL", d.log_level), build_sha=e("BUILD_SHA", d.build_sha), prefix=prefix, parse_errors=errors)

    @property
    def live(self) -> bool:
        return self.env in ("staging", "production")

    def validate(self) -> list[str]:
        p, P = list(self.parse_errors), self.prefix
        if self.env not in ("sandbox", "staging", "production"): p.append(f"{P}ENV must be sandbox, staging or production")
        if self.auth not in ("mock", "oidc"): p.append(f"{P}AUTH must be mock or oidc")
        if self.live and self.auth == "mock": p.append("mock identity is refused in staging and production")
        if self.assistant not in ("fake", "http", "bedrock"): p.append(f"{P}ASSISTANT must be fake, http or bedrock")
        if self.live and self.assistant == "fake": p.append("the fake assistant is refused in staging and production")
        if not 1 <= self.listen_port <= 65535: p.append(f"{P}LISTEN_PORT out of range")
        if not 100 <= self.bedrock_max_output_tokens <= 100_000: p.append(f"{P}BEDROCK_MAX_OUTPUT_TOKENS out of range")
        for name, path in (("IDENTITY_MAP", self.identity_map), ("CONSUMERS_FILE", self.consumers_file), ("COLLECTION_FILE", self.collection_file), ("GUIDE_FILE", self.guide_file)):
            if not os.path.isfile(path): p.append(f"{P}{name} does not exist"); continue
            try:
                with open(path, encoding="utf-8") as f: json.load(f)
            except (OSError, ValueError): p.append(f"{P}{name} is not readable JSON")
        if self.secrets.startswith("file:") and not os.path.isfile(self.secrets[5:]): p.append(f"{P}SECRETS names a file that does not exist")
        if self.static_dir and not os.path.isdir(self.static_dir): p.append(f"{P}STATIC_DIR is not a directory")
        if self.auth == "oidc" and (not self.idp_issuer or not self.idp_audience): p.append(f"{P}IDP_ISSUER and {P}IDP_AUDIENCE are required with oidc")
        if self.auth == "oidc" and self.idp_issuer and not self.idp_issuer.startswith("https://"): p.append(f"{P}IDP_ISSUER must be https")
        if self.auth == "oidc" and not self.ai_security_group: p.append(f"{P}AI_SECURITY_GROUP is empty: nobody could sign for AI security")
        if self.auth == "oidc" and not self.owner_domain: p.append(f"{P}OWNER_DOMAIN is required with oidc: the owner's handle alone would match the same name at any domain")
        if self.owner_domain and ("@" in self.owner_domain or "/" in self.owner_domain or " " in self.owner_domain): p.append(f"{P}OWNER_DOMAIN must be a bare domain name")
        if self.log_level.upper() not in ("DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"): p.append(f"{P}LOG_LEVEL must be DEBUG, INFO, WARNING, ERROR or CRITICAL")
        if self.auth == "oidc" and self.static_dir and (not self.web_oidc_authority or not self.web_oidc_client_id):
            p.append(f"{P}WEB_OIDC_AUTHORITY and {P}WEB_OIDC_CLIENT_ID are required to serve the hub with oidc (they become /config.js)")
        if self.web_oidc_authority and not self.web_oidc_authority.startswith("https://"): p.append(f"{P}WEB_OIDC_AUTHORITY must be https")
        if not 10_000 <= self.max_body_bytes <= 50_000_000: p.append(f"{P}MAX_BODY_BYTES out of range")
        if not 0 <= self.rate_per_minute <= 100_000: p.append(f"{P}RATE_PER_MINUTE out of range")
        if self.live and self.rate_per_minute == 0: p.append(f"{P}RATE_PER_MINUTE must be above 0 in staging and production")
        if not 60 <= self.idempotency_ttl_s <= 30 * 86_400: p.append(f"{P}IDEMPOTENCY_TTL_S out of range (60 s to 30 days)")
        if not 0 <= self.conversation_retention_days <= 3650: p.append(f"{P}CONVERSATION_RETENTION_DAYS out of range (0 keeps, up to ten years)")
        if self.live and self.conversation_retention_days == 0: p.append(f"{P}CONVERSATION_RETENTION_DAYS must be set in staging and production: a person's conversations are not kept for good")
        if self.assistant == "http" and not self.assistant_url: p.append(f"{P}ASSISTANT_URL is required with the http assistant")
        if self.assistant == "bedrock":
            if not self.bedrock_region: p.append(f"{P}BEDROCK_REGION (or AWS_REGION) is required with the bedrock assistant")
            if not self.bedrock_model_id: p.append(f"{P}BEDROCK_MODEL_ID is required with the bedrock assistant")
        if self.live:
            if self.db_path == ":memory:": p.append(f"{P}DB must be a file path in staging and production (the record must survive a restart)")
            if not self.public_url.startswith("https://"): p.append(f"{P}PUBLIC_URL must be https in staging and production")
            if self.assistant == "bedrock" and not self.bedrock_endpoint: p.append(f"{P}BEDROCK_ENDPOINT (the bank's VPC endpoint) is required in staging and production")
            if self.secrets == "env": p.append(f"{P}SECRETS must be aws or file:<path> in staging and production, not the environment")
        if not (self.secrets in ("env", "aws") or self.secrets.startswith("file:")): p.append(f"{P}SECRETS must be env, aws or file:<path>")
        return p

    def require_valid(self) -> "Settings":
        p = self.validate()
        if p:
            raise ConfigError("; ".join(p))
        return self

    def web_config(self) -> dict:
        """What the browser needs, as VITE_ keys: never a secret (the client id and authority are public by design)."""
        base = self.public_url.rstrip("/")
        cfg = {"VITE_API_MODE": "http", "VITE_API_BASE": "/api", "VITE_AUTH_MODE": "oidc" if self.auth == "oidc" else "mock", "VITE_ROUTER": "browser",
               "VITE_KB_URL": self.kb_url, "VITE_BUILD_SHA": self.build_sha}
        if self.auth == "oidc":
            cfg.update({"VITE_OIDC_AUTHORITY": self.web_oidc_authority, "VITE_OIDC_CLIENT_ID": self.web_oidc_client_id,
                        "VITE_OIDC_REDIRECT_URI": self.web_oidc_redirect_uri or f"{base}/auth/callback", "VITE_OIDC_POST_LOGOUT_URI": self.web_oidc_post_logout_uri or f"{base}/",
                        "VITE_OIDC_SCOPE": self.web_oidc_scope})
        else:
            cfg["HUB_ALLOW_MOCK"] = True   # a production hub build refuses mock identity unless the configuration that names it says so (sandbox only: validate() refuses mock in staging and production)
        return cfg

    def advice(self) -> list[str]:
        """Not problems: things that depend on the identity provider, said once at check-config so they are not found in staging."""
        a, P = [], self.prefix
        if self.auth == "oidc" and self.web_oidc_authority:
            scopes = set(self.web_oidc_scope.split())
            if not scopes - {"openid", "profile", "email", "offline_access"}:
                a.append(f"{P}WEB_OIDC_SCOPE names only the standard scopes. A provider that binds access tokens to an API (Entra ID, for one) then issues a token whose aud is not {P}IDP_AUDIENCE and every call is 401: add the API's scope (for example api://HUB_API_CLIENT_ID/.default)")
            if "offline_access" not in scopes:
                a.append(f"{P}WEB_OIDC_SCOPE has no offline_access: the hub renews sessions in a hidden frame to the provider, which the provider must allow (many do not); with offline_access it uses a refresh token instead")
        return a

    def diagnostics(self) -> dict:
        """Presence and shape only, never a value."""
        out = {}
        for f in fields(self):
            if f.name in ("prefix", "parse_errors"): continue
            v = getattr(self, f.name)
            out[f.name] = v if f.name in ("env", "auth", "assistant", "secrets", "log_level", "listen_port") else ("unset" if v in ("", None) else "set")
        return out


def check_config(prefix: str = "HUB_", out=sys.stdout) -> int:
    s = Settings.from_env(prefix)
    problems = s.validate()
    if problems:
        for p in problems: print("config:", p, file=out)
        return 2
    for a in (s.advice() if hasattr(s, "advice") else []): print("note:", a, file=out)
    print("config ok", file=out)
    return 0
