# The walkthrough of the Collection: the hub, the knowledge base and the components, for the first AI champions
# meeting. SLIDES is the authoritative source; deck.py in components/skills/walkthrough-video renders it.
# (id, kicker, title, bullets, shot, narration)
TITLE = "The Collection: walkthrough"
FOOT = "The Collection · walkthrough v1 · AI champions · internal"
SLIDES = [
    ("title", "AI champions", "The Collection, in six minutes", ["One repository: the hub, the knowledge base, the components", "What each engineer can reuse today", "How the programme runs"], None,
     "This is the Collection: the company's AI enablement in one repository. In the next six minutes we walk through the three parts, the hub people open, the knowledge base they read, and the components engineers copy, and then how the AI champions programme uses them."),
    ("three", "The shape", "Three parts, one repository", ["hub: Discover, My workspace, Build, Learn", "knowledgebase: pages the librarian keeps healthy", "components: 23 self-contained pieces with tests", "one catalog tool publishes the components to the other two"], None,
     "Three parts. The hub is the front door: Discover, My workspace, Build and Learn. The knowledge base holds what people read, and a librarian agent keeps it accurate. The components are twenty-three self-contained pieces lifted from two products that run in production, each with a five-minute README, a manifest and tests. One catalog tool publishes every component to the hub and to the knowledge base, so there is a single source and three views."),
    ("discover", "The hub · Discover", "Every component is a listing on Discover", ["The Tools and APIs tab lists the components", "Language, status and origin on every card", "The artboard's default view is untouched"], "01-discover-tools.png",
     "Step one, the hub. Open Discover and the Tools and APIs tab. Every component of the collection is a listing here, with its language, its status and where it came from. The default view stays pixel-identical to the design; the components appear under their tab and in search."),
    ("listing", "The hub · a listing", "A listing page built from the README", ["What it does and the rules it enforces", "What is inside, file by file", "Get started in three steps", "The knowledge-base page as evidence"], "02-listing.png",
     "Open one. The governed action loop is the core of the first responder: the loop an agent runs inside. Its page is generated from its README: what it is for, the rules it enforces, what is inside file by file, and how to get started. Nothing is typed twice."),
    ("search", "The hub · search", "Command-K finds it", ["Assistants, agents, knowledge and components in one search", "A question that matches nothing goes to the assistant"], "03-search.png",
     "Command K searches everything the person may see, components included. Type guard and the untrusted-input guard is one keystroke away."),
    ("learn", "The hub · Learn", "Learn links the three parts together", ["The collection, the knowledge base and the champions programme", "The six roads and the fifteen-minute example", "Start a brief from here"], "04-learn.png",
     "Learn ties the parts together: the collection on Discover, the knowledge base with its practices, and the champions programme with its brief. The six roads and the fifteen-minute example are the same as before."),
    ("kb", "The knowledge base", "Every component has a page the librarian audits", ["A components section with one page per component", "Frontmatter: owner, status, reviewed, tags, audience", "Freshness, links and sensitive content checked in CI"], "06-kb-components.png",
     "Step two, the knowledge base. The catalog tool publishes each component's README as a page in a components section. Every page carries an owner, a review date, tags from the taxonomy and an audience, and the librarian checks freshness, links and sensitive content on every change."),
    ("practice", "The knowledge base · practices", "The practices behind the components", ["Action tiers and confirmation", "Untrusted input and the taint ceiling", "Fail closed, secrets by name, ids-only logs", "The chained record; demonstrations as acceptance"], "07-kb-practice.png",
     "The practices are pages too. Action tiers and confirmation: the tier on the catalog entry decides who says yes, and the model never does. Untrusted input: text a model reads is evidence, and an instruction in it caps the session to reads. Each practice names the component that implements it."),
    ("skills", "The knowledge base · skills", "Skills: procedures people and agents follow", ["Use case to backlog, security notes, readiness, runbook, handover", "Walkthrough video, pixel parity", "Each in the knowledge base's SKILL format, with templates and scripts"], "09-kb-skills.png",
     "Skills are procedures a person or an agent follows: turning a use case into a backlog, writing the security notes, the readiness page, the runbook, the handover, and building a video like this one. They sit in the skills catalog next to the existing ones."),
    ("example", "The components · in a terminal", "A component runs in a minute", ["python3 example.py: admit, read, a write parked, confirmed once, a mitigation refused", "Standard library only; no account needed", "Copy the directory and replace the fakes"], "10-term-example.png",
     "Step three, the components. In a terminal, the governed action loop's example runs end to end: a person is admitted, a read goes through, a write is parked until she confirms it once, a mitigation is refused without a second person, and the record verifies. Standard library only; copy the directory and replace the fakes with your clients."),
    ("tests", "The components · tests", "Every component proves itself", ["One test command per component, in its manifest", "The catalog tool runs them all", "Sixty-one Python tests, twenty-one TypeScript tests, the skill scripts"], "11-term-tests.png",
     "Every component has one test command in its manifest, and the catalog tool runs them all. Sixty-one Python tests, twenty-one TypeScript tests and the skill scripts pass in CI on every change."),
    ("catalog", "The components · the catalog tool", "One tool keeps the three in step", ["Validates manifests and tags against the taxonomy", "Refuses drift in vendored files", "Writes the hub listings and the knowledge-base pages", "Refuses stale exports in CI"], "13-term-check.png",
     "The catalog tool is the glue. It validates every manifest, checks tags against the knowledge base's taxonomy, refuses drift in vendored files, writes the hub's listings and the knowledge base's pages, and in CI refuses a stale export. Add a component, run write, and it is everywhere."),
    ("champions", "The programme", "AI champions: one engineer per team, every two weeks", ["Ten minutes what shipped, twenty a deep dive, fifteen the collection", "One initiative each, built from the collection on a paved road", "Something returned every time: a component, a page, a corpus entry"], "08-kb-champions.png",
     "Now the programme. One engineer per team, meeting every two weeks for forty-five minutes: ten on what shipped, twenty on one deep dive, fifteen on the collection. Each champion carries one initiative built from the collection on a paved road, and returns something every time: a component, a fake, a page, a corpus entry."),
    ("brief", "The programme · the brief", "An initiative starts as a one-page brief", ["Filed through the hub's intake: a road, a risk tier, a reviewer", "What it reuses from the collection, what it returns", "A demonstration with numbers within six weeks"], "05-intake.png",
     "An initiative starts as a one-page brief filed through the hub's intake, so it gets a road, a risk tier and a reviewer. The brief names what it reuses from the collection and what it returns, and ends in a demonstration with numbers within six weeks."),
    ("start", "Getting started", "Your first hour", ["Clone the repository; run one component's tests", "Read one practice page in the knowledge base", "Write the first draft of your brief", "Bring it to the next meeting"], None,
     "Getting started takes an hour. Clone the repository and run one component's tests. Read one practice page. Write the first draft of your brief, and bring it to the next meeting. Thank you."),
]
