#!/usr/bin/env python3
"""The catalog tool: validates every component manifest, checks vendored copies, regenerates CATALOG.md, runs tests.

    python3 tools/catalog.py --check          # manifests valid, vendored files identical, CATALOG.md current (CI)
    python3 tools/catalog.py --write          # regenerate CATALOG.md
    python3 tools/catalog.py --test           # run every component's test command (add --only python|typescript|skills)
    python3 tools/catalog.py --list           # one line per component

Standard library only. A component is a directory under components/ that holds a `component.json` (the contract is
in CONTRIBUTING.md). Nothing here reads a component's code; the manifest is the interface.
"""
from __future__ import annotations
import argparse, json, os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COMPONENTS = os.path.join(ROOT, "components")
CATALOG_MD = os.path.join(ROOT, "CATALOG.md")

KINDS = ("tool", "integration", "skill", "pattern")
LANGUAGES = ("python", "typescript", "markdown", "mixed")
STATUSES = ("ready", "draft", "deprecated")
REQUIRED = ("name", "kind", "language", "summary", "status", "source", "owner", "tags", "test")
KIND_LABEL = {"tool": "Tools", "integration": "Integrations", "skill": "Skills", "pattern": "Patterns"}


class CatalogError(Exception):
    pass


def find_manifests() -> list[str]:
    out = []
    for dirpath, dirnames, filenames in os.walk(COMPONENTS):
        dirnames[:] = [d for d in dirnames if d not in ("node_modules", "__pycache__", "_template", ".git")]
        if "component.json" in filenames:
            out.append(os.path.join(dirpath, "component.json"))
    return sorted(out)


def load(path: str) -> dict:
    with open(path, encoding="utf-8") as f:
        try:
            m = json.load(f)
        except ValueError as e:
            raise CatalogError(f"{rel(path)}: not valid JSON ({e})")
    m["_dir"] = os.path.dirname(path)
    m["_rel"] = rel(os.path.dirname(path))
    return m


def rel(path: str) -> str:
    return os.path.relpath(path, ROOT).replace(os.sep, "/")


def validate(m: dict) -> list[str]:
    p = []
    for k in REQUIRED:
        if k not in m:
            p.append(f"missing field `{k}`")
    if p:
        return p
    if m["name"] != os.path.basename(m["_dir"]):
        p.append(f"name `{m['name']}` does not match its directory `{os.path.basename(m['_dir'])}`")
    if m["kind"] not in KINDS: p.append(f"kind must be one of {KINDS}")
    if m["language"] not in LANGUAGES: p.append(f"language must be one of {LANGUAGES}")
    if m["status"] not in STATUSES: p.append(f"status must be one of {STATUSES}")
    if not isinstance(m["tags"], list) or not m["tags"]: p.append("tags must be a non-empty list")
    if not isinstance(m["source"], dict) or "project" not in m["source"]: p.append("source must be an object with at least `project`")
    if len(m["summary"]) > 160: p.append("summary is longer than 160 characters")
    if not os.path.exists(os.path.join(m["_dir"], "README.md")): p.append("README.md is missing")
    if m["kind"] == "skill" and not os.path.exists(os.path.join(m["_dir"], "SKILL.md")): p.append("a skill needs SKILL.md")
    if m["language"] in ("python", "typescript", "mixed") and not m["test"]: p.append("a code component needs a test command")
    for v in m.get("vendored", []):
        if not isinstance(v, dict) or "path" not in v or "from" not in v:
            p.append("vendored entries are {path, from}"); continue
        here, there = os.path.join(m["_dir"], v["path"]), os.path.join(ROOT, v["from"])
        if not os.path.exists(here): p.append(f"vendored file {v['path']} is missing")
        elif not os.path.exists(there): p.append(f"vendored source {v['from']} does not exist")
        elif open(here, "rb").read() != open(there, "rb").read(): p.append(f"vendored file {v['path']} differs from {v['from']}; copy it again")
    for dep in m.get("pairs_with", []):
        if not any(os.path.basename(d) == dep for d in all_dirs()):
            p.append(f"pairs_with names an unknown component `{dep}`")
    return p


_dirs: list[str] | None = None


def all_dirs() -> list[str]:
    global _dirs
    if _dirs is None:
        _dirs = [os.path.dirname(x) for x in find_manifests()]
    return _dirs


def render(ms: list[dict]) -> str:
    lines = ["# Catalog", "", "Generated by `python3 tools/catalog.py --write`; do not edit by hand. One line per component; the README in each directory is the five-minute introduction.", ""]
    total = len(ms)
    ready = sum(1 for m in ms if m["status"] == "ready")
    lines += [f"{total} components, {ready} ready. Kinds: " + ", ".join(f"{KIND_LABEL[k].lower()} {sum(1 for m in ms if m['kind'] == k)}" for k in KINDS if any(m["kind"] == k for m in ms)), ""]
    for kind in KINDS:
        group = [m for m in ms if m["kind"] == kind]
        if not group: continue
        lines += [f"## {KIND_LABEL[kind]}", "", "| Component | Language | Status | Summary | From | Tags |", "| --- | --- | --- | --- | --- | --- |"]
        for m in group:
            src = m["source"].get("project", "")
            if m["source"].get("path"): src += f" (`{m['source']['path']}`)"
            lines.append(f"| [{m['name']}]({m['_rel']}/) | {m['language']} | {m['status']} | {m['summary']} | {src} | {', '.join(m['tags'])} |")
        lines.append("")
    lines += ["## By tag", ""]
    tags: dict[str, list[str]] = {}
    for m in ms:
        for t in m["tags"]:
            tags.setdefault(t, []).append(f"[{m['name']}]({m['_rel']}/)")
    for t in sorted(tags):
        lines.append(f"- **{t}**: " + ", ".join(tags[t]))
    lines.append("")
    return "\n".join(lines)


def run_tests(ms: list[dict], only: str | None) -> int:
    failures = 0
    for m in ms:
        if only and m["language"] != only and not (only == "skills" and m["kind"] == "skill"):
            continue
        if not m["test"]:
            print(f"-- {m['name']}: no test command"); continue
        print(f"== {m['name']}: {m['test']}", flush=True)
        r = subprocess.run(m["test"], shell=True, cwd=m["_dir"])
        if r.returncode != 0:
            failures += 1; print(f"!! {m['name']} failed ({r.returncode})", flush=True)
    return failures


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true"); ap.add_argument("--write", action="store_true")
    ap.add_argument("--test", action="store_true"); ap.add_argument("--list", action="store_true")
    ap.add_argument("--only", choices=("python", "typescript", "markdown", "mixed", "skills"))
    a = ap.parse_args(argv)
    if not (a.check or a.write or a.test or a.list):
        ap.print_help(); return 2
    ms = []
    problems = []
    for path in find_manifests():
        try:
            m = load(path)
        except CatalogError as e:
            problems.append(str(e)); continue
        for p in validate(m):
            problems.append(f"{m['_rel']}: {p}")
        ms.append(m)
    ms.sort(key=lambda m: (KINDS.index(m["kind"]), m["name"]))
    if problems:
        print("\n".join(problems)); return 1
    if a.list:
        for m in ms: print(f"{m['kind']:<12}{m['language']:<12}{m['status']:<12}{m['name']:<32}{m['summary']}")
    if a.write:
        open(CATALOG_MD, "w", encoding="utf-8").write(render(ms)); print(f"wrote CATALOG.md ({len(ms)} components)")
    if a.check:
        current = open(CATALOG_MD, encoding="utf-8").read() if os.path.exists(CATALOG_MD) else ""
        if current != render(ms):
            print("CATALOG.md is stale: run python3 tools/catalog.py --write"); return 1
        print(f"ok: {len(ms)} manifests valid, vendored copies identical, CATALOG.md current")
    if a.test:
        f = run_tests(ms, a.only)
        print(f"{'FAILED' if f else 'ok'}: {f} component test suite(s) failed" if f else "ok: every component test suite passed")
        return 1 if f else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
